// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = process.platform === 'linux' && process.type === 'renderer' ? require('remote').process.atomBinding('clipboard') : process.atomBinding('clipboard');

}).call(this);
